import React from 'react';
import { ReportData, BulkAnalysisSummary } from '../types';
import { Download } from 'lucide-react';

interface Props {
  report: ReportData;
  summary: BulkAnalysisSummary;
}

const ReportView: React.FC<Props> = ({ report, summary }) => {
  return (
    <div className="bg-white text-slate-900 p-8 rounded-xl shadow-xl max-w-4xl mx-auto">
      <div className="flex justify-between items-start mb-8 border-b border-slate-200 pb-6">
        <div>
            <h1 className="text-3xl font-bold text-slate-900">Review Authenticity Audit</h1>
            <p className="text-slate-500 mt-1">Generated by FAKE REVIEW SYSTEM</p>
        </div>
        <div className="text-right">
             <p className="text-sm text-slate-500">Date</p>
             <p className="font-medium">{new Date().toLocaleDateString()}</p>
        </div>
      </div>

      <div className="grid grid-cols-3 gap-6 mb-8">
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
            <p className="text-sm text-slate-500 uppercase tracking-wider font-semibold">Total Reviews</p>
            <p className="text-2xl font-bold text-slate-900">{summary.totalReviews}</p>
        </div>
        <div className="bg-red-50 p-4 rounded-lg border border-red-100">
            <p className="text-sm text-red-600 uppercase tracking-wider font-semibold">Fake Detected</p>
            <p className="text-2xl font-bold text-red-700">{summary.fakeCount} <span className="text-sm font-normal">({((summary.fakeCount / summary.totalReviews) * 100).toFixed(1)}%)</span></p>
        </div>
        <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
            <p className="text-sm text-blue-600 uppercase tracking-wider font-semibold">Trust Score</p>
            <p className="text-2xl font-bold text-blue-700">{summary.overallTrustScore}/100</p>
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-l-4 border-blue-600 pl-3">Executive Summary</h2>
        <p className="text-slate-700 leading-relaxed">{report.summary}</p>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-l-4 border-red-500 pl-3">Detected Patterns</h2>
        <ul className="list-disc pl-5 space-y-2 text-slate-700">
            {report.keyPatterns.map((pattern, idx) => (
                <li key={idx}>{pattern}</li>
            ))}
        </ul>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-l-4 border-emerald-500 pl-3">Recommendations</h2>
        <ul className="list-disc pl-5 space-y-2 text-slate-700">
            {report.recommendations.map((rec, idx) => (
                <li key={idx}>{rec}</li>
            ))}
        </ul>
      </div>

      <div className="mt-8 pt-6 border-t border-slate-200 flex justify-center print:hidden">
        <button 
            onClick={() => window.print()}
            className="flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-lg hover:bg-slate-800 transition-colors"
        >
            <Download className="w-4 h-4" /> Print / Save as PDF
        </button>
      </div>
    </div>
  );
};

export default ReportView;
