import React from 'react';
import { ReportData, BulkAnalysisSummary } from '../types';
import { Download } from 'lucide-react';

interface Props {
  report: ReportData;
  summary: BulkAnalysisSummary;
}

const ReportView: React.FC<Props> = ({ report, summary }) => {
  const fakePercentage =
    summary.totalReviews > 0
      ? ((summary.fakeCount / summary.totalReviews) * 100).toFixed(1)
      : '0';

  return (
    <div className="bg-white text-slate-900 p-4 sm:p-6 md:p-8 rounded-xl shadow-xl max-w-5xl mx-auto overflow-hidden">
      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between gap-4 sm:gap-6 items-start border-b border-slate-200 pb-6 mb-6 sm:mb-8">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900">
            Review Authenticity Audit
          </h1>

          <p className="text-sm sm:text-base text-slate-500 mt-1">
            Generated by FAKE REVIEW SYSTEM
          </p>
        </div>

        <div className="text-left sm:text-right">
          <p className="text-xs sm:text-sm text-slate-500">
            Date
          </p>

          <p className="font-medium text-sm sm:text-base">
            {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 mb-6 sm:mb-8">
        <div className="bg-slate-50 p-4 rounded-lg border border-slate-200">
          <p className="text-xs sm:text-sm text-slate-500 uppercase tracking-wider font-semibold">
            Total Reviews
          </p>

          <p className="text-xl sm:text-2xl font-bold text-slate-900 mt-1">
            {summary.totalReviews}
          </p>
        </div>

        <div className="bg-red-50 p-4 rounded-lg border border-red-100">
          <p className="text-xs sm:text-sm text-red-600 uppercase tracking-wider font-semibold">
            Fake Detected
          </p>

          <p className="text-xl sm:text-2xl font-bold text-red-700 mt-1">
            {summary.fakeCount}
            <span className="text-xs sm:text-sm font-normal ml-2">
              ({fakePercentage}%)
            </span>
          </p>
        </div>

        <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 sm:col-span-2 lg:col-span-1">
          <p className="text-xs sm:text-sm text-blue-600 uppercase tracking-wider font-semibold">
            Trust Score
          </p>

          <p className="text-xl sm:text-2xl font-bold text-blue-700 mt-1">
            {summary.overallTrustScore}/100
          </p>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="mb-6 sm:mb-8">
        <h2 className="text-lg sm:text-xl font-bold mb-3 border-l-4 border-blue-600 pl-3">
          Executive Summary
        </h2>

        <p className="text-sm sm:text-base text-slate-700 leading-relaxed break-words">
          {report.summary}
        </p>
      </div>

      {/* Detected Patterns */}
      <div className="mb-6 sm:mb-8">
        <h2 className="text-lg sm:text-xl font-bold mb-3 border-l-4 border-red-500 pl-3">
          Detected Patterns
        </h2>

        <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-slate-700">
          {report.keyPatterns.map((pattern, idx) => (
            <li key={idx} className="break-words">
              {pattern}
            </li>
          ))}
        </ul>
      </div>

      {/* Recommendations */}
      <div className="mb-6 sm:mb-8">
        <h2 className="text-lg sm:text-xl font-bold mb-3 border-l-4 border-emerald-500 pl-3">
          Recommendations
        </h2>

        <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base text-slate-700">
          {report.recommendations.map((rec, idx) => (
            <li key={idx} className="break-words">
              {rec}
            </li>
          ))}
        </ul>
      </div>

      {/* Footer Button */}
      <div className="mt-8 pt-6 border-t border-slate-200 flex justify-center print:hidden">
        <button
          onClick={() => window.print()}
          className="w-full sm:w-auto flex items-center justify-center gap-2 bg-slate-900 text-white px-4 sm:px-6 py-3 rounded-lg hover:bg-slate-800 transition-colors text-sm sm:text-base"
        >
          <Download className="w-4 h-4" />
          Print / Save as PDF
        </button>
      </div>
    </div>
  );
};

export default ReportView;
